ASSETS:
  MAA.N:
    constr: 0.035
  ESS.N:
    constr: 0.035
  JBHT.OQ:
    constr: 0.035
  DOV.N:
    constr: 0.035
  VFC.N:
    constr: 0.035
  PPL.N:
    constr: 0.035
  CMCSA.OQ:
    constr: 0.035
  PGR.N:
    constr: 0.035
  CMA.N:
    constr: 0.035
  MCD.N:
    constr: 0.035
  APA.OQ:
    constr: 0.035
  PPG.N:
    constr: 0.035
  MS.N:
    constr: 0.035
  ITW.N:
    constr: 0.035
  FICO.N:
    constr: 0.035
  FAST.OQ:
    constr: 0.035
  UPS.N:
    constr: 0.035
  HUM.N:
    constr: 0.035
  XRAY.OQ:
    constr: 0.035
  CPT.N:
    constr: 0.035
  CPB.N:
    constr: 0.035
  TJX.N:
    constr: 0.035
  BAX.N:
    constr: 0.035
  CAG.N:
    constr: 0.035
  WEC.N:
    constr: 0.035
  NTAP.OQ:
    constr: 0.035
  MAA.N:
    constr: 0.035
  MRO.N:
    constr: 0.035
  CHRW.OQ:
    constr: 0.035
  SPG.N:
    constr: 0.035
  MTB.N:
    constr: 0.035
  ADI.OQ:
    constr: 0.035
  BLK.N:
    constr: 0.035
  COP.N:
    constr: 0.035
  BEN.N:
    constr: 0.035
  DOV.N:
    constr: 0.035
  HWM.N:
    constr: 0.035
  NTRS.OQ:
    constr: 0.035
  ETN.N:
    constr: 0.035
  CLX.N:
    constr: 0.035
  MSI.N:
    constr: 0.035
  MO.N:
    constr: 0.035
  CI.N:
    constr: 0.035
  DRI.N:
    constr: 0.035
  UPS.N:
    constr: 0.035
  PHM.N:
    constr: 0.035
  JKHY.OQ:
    constr: 0.035
  GILD.OQ:
    constr: 0.035
  TFX.N:
    constr: 0.035
  AON.N:
    constr: 0.035
  SNA.N:
    constr: 0.035
  NVR.N:
    constr: 0.035
  TXT.N:
    constr: 0.035
  EMR.N:
    constr: 0.035
  ADSK.OQ:
    constr: 0.035
  PTC.OQ:
    constr: 0.035
  WMT.N:
    constr: 0.035
  WEC.N:
    constr: 0.035
  MKC.N:
    constr: 0.035
  CMS.N:
    constr: 0.035
  ARE.N:
    constr: 0.035
  ABT.N:
    constr: 0.035
  K.N:
    constr: 0.035
  MKC.N:
    constr: 0.035
  MCD.N:
    constr: 0.035
  DE.N:
    constr: 0.035
  BIIB.OQ:
    constr: 0.035
  HSIC.OQ:
    constr: 0.035
  KLAC.OQ:
    constr: 0.035
  AMAT.OQ:
    constr: 0.035
  UNP.N:
    constr: 0.035
  NEM.N:
    constr: 0.035
  EA.OQ:
    constr: 0.035
  RE.N:
    constr: 0.035
MODEL:
  hybrid: False
  main_factors:
    PCA: 5
  secondary_factors: []
  regression_method: ols

CONSTRAINTS:
  allow_short_selling: True
  allow_leverage: True


