rics_examples = {

        "Apple Inc.": "AAPL.OQ",
        "Microsoft Corporation": "MSFT.OQ",
        "Amazon.com Inc.": "AMZN.OQ",
        "Alphabet Inc. Class A": "GOOGL.OQ",
        "Facebook Inc.": "FB.OQ",
        "Tesla Inc.": "TSLA.OQ",
        "NVIDIA Corporation": "NVDA.OQ",
        "JPMorgan Chase & Co.": "JPM.N",
        "Visa Inc.": "V.N",
        "Johnson & Johnson": "JNJ.N",
        "Procter & Gamble Company": "PG.N",
        "Berkshire Hathaway Inc. Class B": "BRKb.N",
        "Walmart Inc.": "WMT.N",
        "Mastercard Incorporated": "MA.N",
        "UnitedHealth Group Incorporated": "UNH.N",
        "Home Depot Inc.": "HD.N",
        "Pfizer Inc.": "PFE.N",
        "Verizon Communications Inc.": "VZ.N",
        "Cisco Systems Inc.": "CSCO.OQ",
        "Netflix Inc.": "NFLX.OQ",
        "Adobe Inc.": "ADBE.OQ",
        "Coca-Cola Company": "KO.N",
        "McDonald's Corporation": "MCD.N",
        "Walt Disney Company": "DIS.N",
        "IBM": "IBM.N",
        "AT&T Inc.": "T.N",
        "Intel Corporation": "INTC.OQ",
        "Salesforce.com Inc.": "CRM.N",
        "Boeing Company": "BA.N",
        "Exxon Mobil Corporation": "XOM.N",
        "Oracle Corporation": "ORCL.N",
        "General Electric Company": "GE.N",
        "Goldman Sachs Group Inc.": "GS.N",
        "Visa Inc. Class A": "VISA.N",
        "Starbucks Corporation": "SBUX.OQ",
        "AbbVie Inc.": "ABBV.N",
        "3M Company": "MMM.N",
        "Bristol-Myers Squibb Company": "BMY.N",
        "General Motors Company": "GM.N",
        "Adobe Inc.": "ADOBE.OQ",
        "Nike Inc.": "NKE.N",
        "Bank of America Corporation": "BAC.N",
        "Pfizer Inc.": "PFIZ.N",
        "Merck & Co. Inc.": "MRK.N",
        "Caterpillar Inc.": "CAT.N",
        "Chevron Corporation": "CVX.N",
        "Amgen Inc.": "AMGN.OQ",
        "Texas Instruments Incorporated": "TXN.OQ",
        "Visa Inc. Class B": "VISA.N",
        "Verizon Communications Inc.": "VZ.N",
        "Coca-Cola Company": "COKE.OQ",
        "Cisco Systems Inc.": "CSCO.N",
        "Exxon Mobil Corporation": "XOM.N",
        "UnitedHealth Group Incorporated": "UNH.N",
        "JPMorgan Chase & Co.": "JPM.N",
        "Wells Fargo & Company": "WFC.N",
        "American Express Company": "AXP.N",
        "Walmart Inc.": "WMT.N",
        "Citigroup Inc.": "C.N",
        "Walt Disney Company": "DIS.N"
}